apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: velero
  namespace: kube-system
  labels:
    component: velero
spec:
  repo: https://vmware-tanzu.github.io/helm-charts
  chart: velero
  targetNamespace: velero
  valuesContent: |-
    deployRestic: true

    credentials:
      secretContents:
        cloud: |
          [default]
          aws_access_key_id = minio
          aws_secret_access_key = minio123

    configuration:
      defaultVolumesToRestic: true
      snapshotsEnabled: false

      provider: aws

      backupStorageLocation:
        name: default
        provider: aws
        bucket: velero
        config:
          s3Url: http://minio:9000
          s3ForcePathStyle: "true"
          region: minio

    initContainers:
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:v1.4.0
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /target
          name: plugins
