---
kind: Namespace
apiVersion: v1
metadata:
  name: test
  labels:
    name: test
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-volume-pvc
  namespace: test
  annotations:
    volumeType: local
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 128Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: volume-test
  namespace: test
  labels:
    name: volume-test
spec:
  containers:
  - name: busybox
    image: busybox
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: volume1
      mountPath: /data
    command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done"]
  volumes:
  - name: volume1
    persistentVolumeClaim:
      claimName: local-volume-pvc