---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: helm-release
  namespace: default
spec:
  chart:
    spec:
      chart: app-template
      version: 0.2.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  interval: 5m
  values:
    image:
      repository: busybox
      tag: 1.35.0
    command: ["tail", "-f", "/dev/null"]
    service:
      main:
        enabled: false
    persistence:
      config:
        enabled: true
        retain: true
