---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: helm-chart
  namespace: kube-system
  labels:
    component: helm-chart
spec:
  repo: https://bjw-s.github.io/helm-charts
  chart: app-template
  targetNamespace: default
  valuesContent: |-
    image:
      repository: busybox
      tag: 1.35.0
    command: ["tail", "-f", "/dev/null"]
    service:
      main:
        enabled: false
    persistence:
      config:
        enabled: true
        retain: true
    