---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: radarr
  namespace: kube-system
  labels:
    component: radarr
spec:
  repo: https://k8s-at-home.com/charts/
  chart: radarr
  targetNamespace: test
  valuesContent: |-
    image:
      repository: ghcr.io/k8s-at-home/radarr
      tag: v4.2.4.6635
    persistence:
      config:
        enabled: true
        retain: true
    